# Generated by Django 3.2.6 on 2021-08-20 06:19

from django.db import migrations, models
import prayers_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='title',
            field=models.CharField(max_length=100, validators=[prayers_app.models.basic_validator]),
        ),
    ]
